### PR TITLE
Adding onSubmitEditing listener

### PR DESCRIPTION
**Pull request by abhishekdewan101**
Hi I came across the following scenario:

1. You use the change text listener to keep track of what the user is typing.
2. You want to initiate search on hitting enter or return.

I do realize that this may not be initial intention of the library, however I think it might be a nice addition to this.

### CODE REVIEW

**Comment by abhishekdewan101** [comment]
@WrathChaos tagging you in this PR enhancement

**Comment by WrathChaos** [comment]
Hello @abhishekdewan101 , Thank you for this awesome contribution. Let me test it first then I can merge and release a new version :)

**Comment by WrathChaos** [comment]
Hello @abhishekdewan101 ,
I've just merged this PR. However, I made the change and made the TextInput fully customizable with the ES6's new rest feature as `...this.props` :) 

Check the new release out : 
# [Release 0.3.1 🥳🤩 ](https://github.com/WrathChaos/react-native-dynamic-search-bar/releases/tag/0.3.1)

**Comment by abhishekdewan101** [comment]
@WrathChaos awesome looks great :)

**Pull request merged**
